CC = g++
CFLAGS = -Wall -Wextra -O3

PART1 = part1
PART2 = part2

all: $(PART1) $(PART2)

$(PART1): part1.cpp
	$(CC) $(CFLAGS) part1.cpp -o $(PART1)

$(PART2): part2.cpp
	$(CC) $(CFLAGS) part2.cpp -o $(PART2)

clean:
	rm -f $(PART1) $(PART2)

